// ---
// label: profile README generator
// role: Render the GitHub profile README (brandonmrgich/brandonmrgich) from the same
//   data files that render the website, so the two cannot drift apart.
// invariants:
//   - Reads only src/data/*.json. If a fact is not in those files it does not belong
//     here either — the whole point is one source of truth for both surfaces.
//   - Private entries are named and described but never linked, matching the site.
//   - Output carries a generated-by banner. Hand-editing the profile repo's README is
//     a mistake that the next run silently reverts, so the file says so.
// gotchas:
//   - GitHub profile READMEs render in a narrow column. Keep to short lines and simple
//     lists; wide tables get cut off on the profile page even though they look fine in
//     the repo view.
//   - This writes to dist/PROFILE.md, NOT to the profile repo. Publishing is a separate
//     explicit step (pnpm profile:publish) because it pushes to a different repository.
// last-touched: 2026-08-10
// ---
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const read = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'))

const resume = read('src/data/resume.json')
const projects = read('src/data/projects.json')

const { basics } = resume
const current = resume.work
  .filter((w) => !w.endDate)
  .sort((a, b) => b.startDate.localeCompare(a.startDate))[0]

const out = []
const push = (...lines) => out.push(...lines)

push(
  '<!-- Generated by scripts/build-profile.mjs in brandonmrgich/dev-portfolio.',
  '     Edits made directly to this file are reverted on the next run.',
  '     Change src/data/resume.json or src/data/projects.json instead. -->',
  '',
  `## ${basics.name}`,
  '',
)

if (current) {
  const at = current.client ? `${current.name} at ${current.client}` : current.name
  // No trailing double-space: the hard line break existed to bind a location line
  // underneath, and `basics.location` is gone (see `_locationNote` in resume.json).
  push(`**${current.position}** · ${at}`, '')
}

push(basics.headline, '', `**Full portfolio → [dev.brandonmrgich.com](https://dev.brandonmrgich.com)**`, '')

// --- selected work --------------------------------------------------------
push('### What I build', '')
for (const p of projects.featured) {
  const title = p.link ? `[${p.name}](${p.link.url})` : p.name
  const mark = p.visibility === 'private' ? ' *(private source)*' : ''
  push(`- **${title}**${mark} — ${p.tagline}`)
}
push('')

// No "Upstream issues filed" section. `upstream` entries stay in projects.json and
// still render on dev.brandonmrgich.com, where they sit under the project that
// explains them. On the profile README they landed as a flat list of bug-tracker
// links with that context stripped, which reads as noise rather than as work.

// --- public repos ---------------------------------------------------------
if (projects.openSource.length) {
  push('### Public repositories', '')
  for (const r of projects.openSource) {
    const name = r.repo.split('/')[1]
    push(`- **[${name}](https://github.com/${r.repo})** — ${r.blurb}`)
  }
  push('')
}

// --- skills ---------------------------------------------------------------
push('### Skills', '')
for (const group of resume.skills) push(`**${group.name}** — ${group.keywords.join(' · ')}  `)
push('')

// --- footer ---------------------------------------------------------------
const links = basics.profiles.map((p) => `[${p.network}](${p.url})`).join(' · ')
push('---', '', links, '')

mkdirSync(join(root, 'dist'), { recursive: true })
writeFileSync(join(root, 'dist/PROFILE.md'), out.join('\n'))
console.log(`[profile] wrote dist/PROFILE.md (${out.length} lines)`)
