#!/usr/bin/env bash
# ---
# label: profile publisher
# role: Push the generated dist/PROFILE.md to brandonmrgich/brandonmrgich as README.md,
#   which is what GitHub renders at the top of the user profile page.
# invariants:
#   - Never runs from CI by default. Pushing to a *different* repository needs a PAT,
#     and a portfolio site does not justify storing one. Run it locally after changing
#     the data files.
#   - No-ops when the rendered output is byte-identical to what is already published,
#     so re-running does not create empty commits.
# gotchas:
#   - The profile repo must be public and the README must sit at the root of the
#     default branch, or GitHub silently does not render it on the profile.
# last-touched: 2026-08-10
# ---
set -euo pipefail

REPO="brandonmrgich/brandonmrgich"
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/dist/PROFILE.md"

[[ -f "$SRC" ]] || { echo "missing $SRC — run 'pnpm profile' first" >&2; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

git clone -q --depth 1 "https://github.com/${REPO}.git" "$WORK/repo"
cp "$SRC" "$WORK/repo/README.md"

cd "$WORK/repo"
# Both conditions matter. `git diff` reports nothing for an untracked path, so testing
# it alone would call the very first publish — into an empty repo — a no-op and push
# nothing. Only a file that is already tracked AND unchanged means there is no work.
if git ls-files --error-unmatch README.md >/dev/null 2>&1 && git diff --quiet -- README.md; then
  echo "[profile] already up to date — nothing to publish"
  exit 0
fi

git add README.md
git commit -q -m "Sync profile README from dev-portfolio

Regenerated by scripts/build-profile.mjs. Source of truth is
src/data/resume.json and src/data/projects.json in
brandonmrgich/dev-portfolio — edit there, not here."
git push -q origin HEAD
echo "[profile] published to https://github.com/${REPO}"
